Update files/.husky/pre-commit

diff --git a/files/.husky/pre-commit b/files/.husky/pre-commit
--- a/files/.husky/pre-commit
+++ b/files/.husky/pre-commit
@@ -2,4 +2,8 @@
 . "$(dirname "$0")/_/husky.sh"
 
 npx lint-staged
+echo "Running npm test"
 npm test
+echo "Checking for spelling errors"
+files=$(git diff --cached --name-only)
+npx cspell --no-summary --config ./.modules/shared/.cspell.json $files || echo "Review the list of possible misspelled words above and correct anything that needs changing."
